name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Run CI/CD on push to the main branch

jobs:
  # Continuous Integration
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup PHP environment
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1 # Specify your PHP version
        extensions: mbstring, pdo, tokenizer, xml
        coverage: none

    # Step 3: Run PHP lint
    - name: PHP Lint Check
      run: |
        find . -name "*.php" -exec php -l {} \;

    # Step 4: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use the latest stable version

    # Step 5: Run JavaScript linting
    - name: Lint JavaScript Files
      run: |
        # Generate ESLint configuration file if not present
        if [ ! -f eslint.config.cjs ]; then
          echo "Creating ESLint configuration..."
          echo "module.exports = { root: true, env: { browser: true, es2021: true }, extends: ['eslint:recommended'], parserOptions: { ecmaVersion: 12 }, rules: {} };" > eslint.config.cjs
        fi
        # Install ESLint globally
        npm install -g eslint
        # Run ESLint on all JavaScript files
        eslint -c eslint.config.cjs "**/*.js"

  # Continuous Deployment
  deploy:
    needs: build-and-test # Ensure CI passes before deployment
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Zip the project files
    - name: Archive Project Files
      run: |
        zip -r project.zip . -x "*.git*" -x ".github/*" -x "node_modules/*"

    # Step 3: Deploy to XAMPP Server
    - name: Deploy to XAMPP Server
      run: |
        echo "Starting Deployment..."
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
          -F "project=@project.zip" \
          http://abcd1234.ngrok.io/api/deploy-endpoint.php
        echo "Deployment Complete!"
