name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use the latest stable version

    # Step 3: Install ESLint
    - name: Install ESLint
      run: |
        npm install -g eslint

    # Step 4: Run ESLint
    - name: Lint JavaScript Files
      run: |
        eslint "**/*.js" --config build/npm/.eslintrc.js
