name: CI/CD Pipeline for JavaScript and PHP Project

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  ci_cd:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu runner

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set Node.js version

      # Step 3: Install Dependencies (including ESLint)
      - name: Install Dependencies
        run: |
          npm install  # Install all dependencies including ESLint

      # Step 4: Run JavaScript Linter (ESLint)
      - name: Run JavaScript Linter (ESLint)
        run: |
          npx eslint .  # Use npx to run ESLint locally

      # Step 5: Run PHP Code Sniffer (Optional, if you want to check PHP code quality)
      - name: Run PHP Code Sniffer
        run: |
          sudo apt-get install php-pear php-dev  # Install PHP dependencies
          sudo pear install PHP_CodeSniffer  # Install PHP_CodeSniffer
          phpcs --standard=PSR12 .  # Run PHP CodeSniffer on the project

      # Step 6: Archive Project Files
      - name: Archive Project Files
        run: |
          zip -r project.zip . -x "*.git*" -x ".github/*" -x "node_modules/*"

      # Step 7: Deploy to XAMPP Server (HTTP via ngrok)
      - name: Deploy to XAMPP Server
        run: |
          echo "Starting Deployment..."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            -F "project=@project.zip" \
            http://abcd1234.ngrok.io/api/deploy-endpoint.php
          echo "Deployment Complete!"
