name: Deploy to XAMPP FTP Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftp
        local-dir: ./
        server-dir: /path/to/your/htdocs/
        log-level: verbose
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env

    - name: Deployment Status
      if: success()
      run: echo "Deployment completed successfully!"

    - name: Deployment Failure
      if: failure()
      run: echo "Deployment failed. Check workflow logs for details."
