name: Deploy to XAMPP FTP Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Network Diagnostics
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
      run: |
        sudo apt-get update
        sudo apt-get install -y netcat
        nc -zv $FTP_HOST 21 || echo "Port 21 connection failed"

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftp
        local-dir: ./
        server-dir: /path/to/your/htdocs/
        log-level: verbose
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env
          **/*.log

    - name: Verify Deployment
      run: |
        echo "Deployment completed. Performing basic checks..."
        curl -I ${{ secrets.FTP_HOST }}/index.php || echo "Website health check failed"

    - name: Notify on Failure
      if: failure()
      run: |
        echo "Deployment failed. Check workflow logs for details."
