name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # JavaScript Lint and Test
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install JS Dependencies
        run: npm install

      - name: Run JS Lint
        run: npm run lint

      - name: Run JS Tests
        run: npm test

      # PHP Lint and Test
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install PHP Dependencies
        run: composer install

      - name: Run PHP Lint
        run: composer phpcs

      - name: Run PHP Tests
        run: composer test

      # Deployment
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './dist'
          server-dir: '/public_html'
