name: FTP Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: FTP Deploy
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: '127.0.0.1:14147'               # Correct FTP server address and port
          username: ${{ secrets.FTP_USERNAME }}   # Add FTP username in GitHub secrets
          password: ${{ secrets.FTP_PASSWORD }}   # Add FTP password in GitHub secrets
          local-dir: './'                         # Directory of your project
          server-dir: '/htdocs/'                  # Remote directory (htdocs in your case)
